export enum AuthActionTypes {

  AUTH_REQUEST = 'AUTH_REQUEST',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILURE = 'AUTH_FAILURE',
  
  AUTH_LOGOUT_USER = "AUTH_LOGOUT_USER",
  AUTH_RESET = "AUTH_RESET",
}
