export enum CartActionTypes {
  
  ADD_PRODUCT_TO_CART_REQUEST = 'ADD_PRODUCT_TO_CART_REQUEST',
  ADD_PRODUCT_TO_CART_SUCCCESS = 'ADD_PRODUCT_TO_CART_SUCCCESS',
  ADD_PRODUCT_TO_CART_FAILURE = 'ADD_PRODUCT_TO_CART_FAILURE',
  ADD_PRODUCT_TO_CART_CHECK = 'ADD_PRODUCT_TO_CART_CHECK',
  
}
